### ISSUE TITLE
Error in introduction-to-iterators/problem.md

### ISSUE THREAD

**Issue by bl4de** [jesstelford/esnext-generation#4]
There's an error in problem.md file:

> All subsequent calls to next() will have done set to true

I think it should be:

> All subsequent calls to next() will have done set to false

**Comment by jesstelford** [comment]
The current wording [is correct](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Iteration_protocols#iterator):

> done (boolean)
> - Has the value `true` if the iterator is past the end of the iterated sequence. In this case `value` optionally specifies the _return value_ of the iterator. The return values are explained [here](http://www.2ality.com/2013/06/iterators-generators.html#generators-as-threads).
> - Has the value `false` if the iterator was able to produce the next value in the sequence. This is equivalent of not specifying the done property altogether.
